/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ProblemHelper;

import java.util.Scanner;

public class App {
    private static boolean terminate;

    public static void main(String[] args) throws Exception {
        terminate = false;
        while (!terminate) {
            Scanner sc = new Scanner(System.in);
            System.out.println("Enter a command: ");
            String str = sc.nextLine(); // reads string
            Thread execution = (new Thread(){

                @Override
                public void run() {
                    String[] commands = str.split(" ");
                    if (commands.length > 0) {
                        final String command = commands[0];
                        if (command.equals("build")) {
                            System.out.println("Executing build");
                            try {
                                // Print the hand
                                System.out.println("; Hand \n hand - position \n (hand ?hand)\n");
                                System.out.println(new Fridge(commands).toString());
                            } catch (Exception e) {
                                e.printStackTrace();
                            }
                            System.out.println("Done");
                        } else if (command.equals("close")) {
                            terminate = true;
                            System.out.println("Bye bye");
                        } else {
                            System.out.println("Invalid command");
                        }
                    }
                }
                
            });
            execution.start();
            execution.join();
        }
    }
}

